# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cDAQgui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(305, 291)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/LocalAdmin/Documents/Python Scripts/NewFocus/Images/cDAQ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 250))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TabWidgetcDAQ = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidgetcDAQ.setMouseTracking(False)
        self.TabWidgetcDAQ.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.TabWidgetcDAQ.setTabBarAutoHide(False)
        self.TabWidgetcDAQ.setObjectName("TabWidgetcDAQ")
        self.cDAQ1Mod1 = QtWidgets.QWidget()
        self.cDAQ1Mod1.setObjectName("cDAQ1Mod1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.cDAQ1Mod1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.cDAQ1Mod1)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.cDAQ1Mod2Groupbox = QtWidgets.QGroupBox(self.groupBox)
        self.cDAQ1Mod2Groupbox.setGeometry(QtCore.QRect(0, 0, 251, 171))
        self.cDAQ1Mod2Groupbox.setObjectName("cDAQ1Mod2Groupbox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.cDAQ1Mod2Groupbox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 221, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cDAQ1Mod1ao1label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao1label.setObjectName("cDAQ1Mod1ao1label")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao1label, 2, 0, 1, 1)
        self.cDAQ1Mod1ao3label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao3label.setObjectName("cDAQ1Mod1ao3label")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao3label, 4, 0, 1, 1)
        self.cDAQ1Mod1ActualOLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ActualOLabel.setObjectName("cDAQ1Mod1ActualOLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ActualOLabel, 0, 2, 1, 1)
        self.cDAQ1Mod1ChannelLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ChannelLabel.setObjectName("cDAQ1Mod1ChannelLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ChannelLabel, 0, 0, 1, 1)
        self.cDAQ1Mod1ao2label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao2label.setObjectName("cDAQ1Mod1ao2label")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao2label, 3, 0, 1, 1)
        self.cDAQ1Mod1ao2OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cDAQ1Mod1ao2OLabel.setObjectName("cDAQ1Mod1ao2OLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao2OLabel, 3, 1, 1, 1)
        self.cDAQ1Mod1ao0OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cDAQ1Mod1ao0OLabel.setObjectName("cDAQ1Mod1ao0OLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao0OLabel, 1, 1, 1, 1)
        self.cDAQ1Mod1ao1OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cDAQ1Mod1ao1OLabel.setObjectName("cDAQ1Mod1ao1OLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao1OLabel, 2, 1, 1, 1)
        self.cDAQ1Mod1ao3OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cDAQ1Mod1ao3OLabel.setObjectName("cDAQ1Mod1ao3OLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao3OLabel, 4, 1, 1, 1)
        self.cDAQ1Mod1ao0label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao0label.setObjectName("cDAQ1Mod1ao0label")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao0label, 1, 0, 1, 1)
        self.cDAQ1Mod1SetOLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1SetOLabel.setObjectName("cDAQ1Mod1SetOLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1SetOLabel, 0, 1, 1, 1)
        self.cDAQ1Mod1ao0COLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao0COLabel.setObjectName("cDAQ1Mod1ao0COLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao0COLabel, 1, 2, 1, 1)
        self.cDAQ1Mod1ao1COLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao1COLabel.setObjectName("cDAQ1Mod1ao1COLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao1COLabel, 2, 2, 1, 1)
        self.cDAQ1Mod1ao2COLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao2COLabel.setObjectName("cDAQ1Mod1ao2COLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao2COLabel, 3, 2, 1, 1)
        self.cDAQ1Mod1ao3COLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cDAQ1Mod1ao3COLabel.setObjectName("cDAQ1Mod1ao3COLabel")
        self.gridLayout_7.addWidget(self.cDAQ1Mod1ao3COLabel, 4, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)
        self.TabWidgetcDAQ.addTab(self.cDAQ1Mod1, "")
        self.TabWidgetcDAQModsTab2 = QtWidgets.QWidget()
        self.TabWidgetcDAQModsTab2.setObjectName("TabWidgetcDAQModsTab2")
        self.cDAQ1Mod2Groupbox_2 = QtWidgets.QGroupBox(self.TabWidgetcDAQModsTab2)
        self.cDAQ1Mod2Groupbox_2.setGeometry(QtCore.QRect(10, 10, 251, 171))
        self.cDAQ1Mod2Groupbox_2.setObjectName("cDAQ1Mod2Groupbox_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.cDAQ1Mod2Groupbox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(19, 19, 221, 141))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cDAQ2Mod1ao1label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ2Mod1ao1label.setObjectName("cDAQ2Mod1ao1label")
        self.gridLayout_9.addWidget(self.cDAQ2Mod1ao1label, 2, 0, 1, 1)
        self.cDAQ1Mod2ao3label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao3label.setObjectName("cDAQ1Mod2ao3label")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao3label, 4, 0, 1, 1)
        self.cDAQ1Mod2ActualOLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ActualOLabel.setObjectName("cDAQ1Mod2ActualOLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ActualOLabel, 0, 2, 1, 1)
        self.cDAQ1Mod2ChannelLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ChannelLabel.setObjectName("cDAQ1Mod2ChannelLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ChannelLabel, 0, 0, 1, 1)
        self.cDAQ2Mod2ao2label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ2Mod2ao2label.setObjectName("cDAQ2Mod2ao2label")
        self.gridLayout_9.addWidget(self.cDAQ2Mod2ao2label, 3, 0, 1, 1)
        self.cDAQ1Mod2ao2OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao2OLabel.setObjectName("cDAQ1Mod2ao2OLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao2OLabel, 3, 1, 1, 1)
        self.cDAQ1Mod2ao0OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao0OLabel.setObjectName("cDAQ1Mod2ao0OLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao0OLabel, 1, 1, 1, 1)
        self.cDAQ1Mod2ao1OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao1OLabel.setObjectName("cDAQ1Mod2ao1OLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao1OLabel, 2, 1, 1, 1)
        self.cDAQ1Mod2ao3OLabel = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao3OLabel.setObjectName("cDAQ1Mod2ao3OLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao3OLabel, 4, 1, 1, 1)
        self.cDAQ1Mod2ao0label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao0label.setObjectName("cDAQ1Mod2ao0label")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao0label, 1, 0, 1, 1)
        self.cDAQ1Mod2SetOLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2SetOLabel.setObjectName("cDAQ1Mod2SetOLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2SetOLabel, 0, 1, 1, 1)
        self.cDAQ1Mod2ao0COLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao0COLabel.setObjectName("cDAQ1Mod2ao0COLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao0COLabel, 1, 2, 1, 1)
        self.cDAQ1Mod2ao1COLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao1COLabel.setObjectName("cDAQ1Mod2ao1COLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao1COLabel, 2, 2, 1, 1)
        self.cDAQ1Mod2ao2COLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao2COLabel.setObjectName("cDAQ1Mod2ao2COLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao2COLabel, 3, 2, 1, 1)
        self.cDAQ1Mod2ao3COLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.cDAQ1Mod2ao3COLabel.setObjectName("cDAQ1Mod2ao3COLabel")
        self.gridLayout_9.addWidget(self.cDAQ1Mod2ao3COLabel, 4, 2, 1, 1)
        self.TabWidgetcDAQ.addTab(self.TabWidgetcDAQModsTab2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 111, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.cDAQ1Mod3ai1label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai1label.setObjectName("cDAQ1Mod3ai1label")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai1label, 2, 0, 1, 1)
        self.cDAQ1Mod3ai3label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai3label.setObjectName("cDAQ1Mod3ai3label")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai3label, 4, 0, 1, 1)
        self.cDAQ1Mod3ai2label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai2label.setObjectName("cDAQ1Mod3ai2label")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai2label, 3, 0, 1, 1)
        self.cDAQ1Mod3ChannelLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ChannelLabel.setObjectName("cDAQ1Mod3ChannelLabel")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ChannelLabel, 0, 0, 1, 1)
        self.cDAQ1Mod3InputLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3InputLabel.setObjectName("cDAQ1Mod3InputLabel")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3InputLabel, 0, 1, 1, 1)
        self.cDAQ1Mod3ai0label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai0label.setObjectName("cDAQ1Mod3ai0label")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai0label, 1, 0, 1, 1)
        self.cDAQ1Mod3ai0InputLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai0InputLabel.setObjectName("cDAQ1Mod3ai0InputLabel")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai0InputLabel, 1, 1, 1, 1)
        self.cDAQ1Mod3ai1InputLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai1InputLabel.setObjectName("cDAQ1Mod3ai1InputLabel")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai1InputLabel, 2, 1, 1, 1)
        self.cDAQ1Mod3ai2InputLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai2InputLabel.setObjectName("cDAQ1Mod3ai2InputLabel")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai2InputLabel, 3, 1, 1, 1)
        self.cDAQ1Mod3ai3InputLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.cDAQ1Mod3ai3InputLabel.setObjectName("cDAQ1Mod3ai3InputLabel")
        self.gridLayout_8.addWidget(self.cDAQ1Mod3ai3InputLabel, 4, 1, 1, 1)
        self.checkBoxcDAQ1Mod3LiveDat = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxcDAQ1Mod3LiveDat.setGeometry(QtCore.QRect(10, 170, 287, 17))
        self.checkBoxcDAQ1Mod3LiveDat.setObjectName("checkBoxcDAQ1Mod3LiveDat")
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.TabWidgetcDAQ.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.TabWidgetcDAQ, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 305, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setToolTip("")
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMANN = QtWidgets.QAction(MainWindow)
        self.actionMANN.setObjectName("actionMANN")
        self.menuAbout.addAction(self.actionMANN)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.TabWidgetcDAQ.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cDAQ1Mod1ao0OLabel, self.cDAQ1Mod1ao1OLabel)
        MainWindow.setTabOrder(self.cDAQ1Mod1ao1OLabel, self.cDAQ1Mod1ao2OLabel)
        MainWindow.setTabOrder(self.cDAQ1Mod1ao2OLabel, self.cDAQ1Mod1ao3OLabel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "cDAQ GUI Yellow lab"))
        self.cDAQ1Mod2Groupbox.setTitle(_translate("MainWindow", "Output mod 1"))
        self.cDAQ1Mod1ao1label.setText(_translate("MainWindow", "  ao1"))
        self.cDAQ1Mod1ao3label.setText(_translate("MainWindow", "  ao3"))
        self.cDAQ1Mod1ActualOLabel.setText(_translate("MainWindow", "Current output (V)"))
        self.cDAQ1Mod1ChannelLabel.setText(_translate("MainWindow", "Channel"))
        self.cDAQ1Mod1ao2label.setText(_translate("MainWindow", "  ao2"))
        self.cDAQ1Mod1ao0label.setText(_translate("MainWindow", "  ao0"))
        self.cDAQ1Mod1SetOLabel.setText(_translate("MainWindow", "Set output (V)"))
        self.cDAQ1Mod1ao0COLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod1ao1COLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod1ao2COLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod1ao3COLabel.setText(_translate("MainWindow", "0"))
        self.TabWidgetcDAQ.setTabText(self.TabWidgetcDAQ.indexOf(self.cDAQ1Mod1), _translate("MainWindow", "cDAQ1Mod1"))
        self.cDAQ1Mod2Groupbox_2.setTitle(_translate("MainWindow", "Output mod 1"))
        self.cDAQ2Mod1ao1label.setText(_translate("MainWindow", "  ao1"))
        self.cDAQ1Mod2ao3label.setText(_translate("MainWindow", "  ao3"))
        self.cDAQ1Mod2ActualOLabel.setText(_translate("MainWindow", "Current output (V)"))
        self.cDAQ1Mod2ChannelLabel.setText(_translate("MainWindow", "Channel"))
        self.cDAQ2Mod2ao2label.setText(_translate("MainWindow", "  ao2"))
        self.cDAQ1Mod2ao0label.setText(_translate("MainWindow", "  ao0"))
        self.cDAQ1Mod2SetOLabel.setText(_translate("MainWindow", "Set output (V)"))
        self.cDAQ1Mod2ao0COLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod2ao1COLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod2ao2COLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod2ao3COLabel.setText(_translate("MainWindow", "0"))
        self.TabWidgetcDAQ.setTabText(self.TabWidgetcDAQ.indexOf(self.TabWidgetcDAQModsTab2), _translate("MainWindow", "cDAQ1Mod2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Input mod 3"))
        self.cDAQ1Mod3ai1label.setText(_translate("MainWindow", "  ai1"))
        self.cDAQ1Mod3ai3label.setText(_translate("MainWindow", "  ai3"))
        self.cDAQ1Mod3ai2label.setText(_translate("MainWindow", "  ai2"))
        self.cDAQ1Mod3ChannelLabel.setText(_translate("MainWindow", "Channel"))
        self.cDAQ1Mod3InputLabel.setText(_translate("MainWindow", "Input (V)"))
        self.cDAQ1Mod3ai0label.setText(_translate("MainWindow", "  ai0"))
        self.cDAQ1Mod3ai0InputLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod3ai1InputLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod3ai2InputLabel.setText(_translate("MainWindow", "0"))
        self.cDAQ1Mod3ai3InputLabel.setText(_translate("MainWindow", "0"))
        self.checkBoxcDAQ1Mod3LiveDat.setText(_translate("MainWindow", "Acquire live data"))
        self.TabWidgetcDAQ.setTabText(self.TabWidgetcDAQ.indexOf(self.tab_4), _translate("MainWindow", "cDAQ1Mod3"))
        self.menuAbout.setStatusTip(_translate("MainWindow", "Some generic information on this GUI"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionMANN.setText(_translate("MainWindow", "MANN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

