# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/yellow_coarse_scan_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(275, 498)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.btn_save_txt = QtWidgets.QPushButton(Form)
        self.btn_save_txt.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_save_txt.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_save_txt.setObjectName("btn_save_txt")
        self.verticalLayout_9.addWidget(self.btn_save_txt)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_save.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_9.addWidget(self.btn_save)
        self.gridLayout.addLayout(self.verticalLayout_9, 4, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_save_note = QtWidgets.QLabel(Form)
        self.label_save_note.setObjectName("label_save_note")
        self.verticalLayout_8.addWidget(self.label_save_note)
        self.info_text = QtWidgets.QTextEdit(Form)
        self.info_text.setMinimumSize(QtCore.QSize(100, 0))
        self.info_text.setMaximumSize(QtCore.QSize(100, 400))
        self.info_text.setObjectName("info_text")
        self.verticalLayout_8.addWidget(self.info_text)
        self.gridLayout.addLayout(self.verticalLayout_8, 4, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_wavelength = QtWidgets.QComboBox(Form)
        self.comboBox_wavelength.setObjectName("comboBox_wavelength")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_wavelength)
        self.comboBox_detection = QtWidgets.QComboBox(Form)
        self.comboBox_detection.setObjectName("comboBox_detection")
        self.comboBox_detection.addItem("")
        self.comboBox_detection.addItem("")
        self.comboBox_detection.addItem("")
        self.comboBox_detection.addItem("")
        self.comboBox_detection.addItem("")
        self.comboBox_detection.addItem("")
        self.comboBox_detection.addItem("")
        self.comboBox_detection.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_detection)
        self.comboBox_pd_no_disk = QtWidgets.QComboBox(Form)
        self.comboBox_pd_no_disk.setObjectName("comboBox_pd_no_disk")
        self.comboBox_pd_no_disk.addItem("")
        self.comboBox_pd_no_disk.addItem("")
        self.comboBox_pd_no_disk.addItem("")
        self.comboBox_pd_no_disk.addItem("")
        self.comboBox_pd_no_disk.addItem("")
        self.comboBox_pd_no_disk.addItem("")
        self.comboBox_pd_no_disk.addItem("")
        self.comboBox_pd_no_disk.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_pd_no_disk)
        self.comboBox_test_detection = QtWidgets.QComboBox(Form)
        self.comboBox_test_detection.setObjectName("comboBox_test_detection")
        self.comboBox_test_detection.addItem("")
        self.comboBox_test_detection.addItem("")
        self.comboBox_test_detection.addItem("")
        self.comboBox_test_detection.addItem("")
        self.comboBox_test_detection.addItem("")
        self.comboBox_test_detection.addItem("")
        self.comboBox_test_detection.addItem("")
        self.comboBox_test_detection.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_test_detection)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.edit_wl_stop = QtWidgets.QLineEdit(Form)
        self.edit_wl_stop.setObjectName("edit_wl_stop")
        self.verticalLayout_4.addWidget(self.edit_wl_stop)
        self.lineedit_scanning_speed = QtWidgets.QLineEdit(Form)
        self.lineedit_scanning_speed.setObjectName("lineedit_scanning_speed")
        self.verticalLayout_4.addWidget(self.lineedit_scanning_speed)
        self.comboBox_plotting_coarse_scan = QtWidgets.QComboBox(Form)
        self.comboBox_plotting_coarse_scan.setObjectName("comboBox_plotting_coarse_scan")
        self.comboBox_plotting_coarse_scan.addItem("")
        self.comboBox_plotting_coarse_scan.addItem("")
        self.comboBox_plotting_coarse_scan.addItem("")
        self.comboBox_plotting_coarse_scan.addItem("")
        self.comboBox_plotting_coarse_scan.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_plotting_coarse_scan)
        self.lineEdit_avg_over_x_steps = QtWidgets.QLineEdit(Form)
        self.lineEdit_avg_over_x_steps.setObjectName("lineEdit_avg_over_x_steps")
        self.verticalLayout_4.addWidget(self.lineEdit_avg_over_x_steps)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_scan = QtWidgets.QPushButton(Form)
        self.btn_scan.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_scan.setObjectName("btn_scan")
        self.verticalLayout_2.addWidget(self.btn_scan)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_wavelength = QtWidgets.QLabel(Form)
        self.label_wavelength.setObjectName("label_wavelength")
        self.verticalLayout_3.addWidget(self.label_wavelength)
        self.edit_wl_start = QtWidgets.QLineEdit(Form)
        self.edit_wl_start.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edit_wl_start.setObjectName("edit_wl_start")
        self.verticalLayout_3.addWidget(self.edit_wl_start)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.plot_label = QtWidgets.QLabel(Form)
        self.plot_label.setObjectName("plot_label")
        self.verticalLayout_3.addWidget(self.plot_label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_save_txt.setText(_translate("Form", "save txt"))
        self.btn_save.setText(_translate("Form", "save"))
        self.label_save_note.setText(_translate("Form", "save note:"))
        self.comboBox_wavelength.setItemText(0, _translate("Form", "ai0"))
        self.comboBox_wavelength.setItemText(1, _translate("Form", "ai1"))
        self.comboBox_wavelength.setItemText(2, _translate("Form", "ai2"))
        self.comboBox_wavelength.setItemText(3, _translate("Form", "ai3"))
        self.comboBox_wavelength.setItemText(4, _translate("Form", "ai4"))
        self.comboBox_wavelength.setItemText(5, _translate("Form", "ai5"))
        self.comboBox_wavelength.setItemText(6, _translate("Form", "ai6"))
        self.comboBox_detection.setItemText(0, _translate("Form", "ai0"))
        self.comboBox_detection.setItemText(1, _translate("Form", "ai1"))
        self.comboBox_detection.setItemText(2, _translate("Form", "ai2"))
        self.comboBox_detection.setItemText(3, _translate("Form", "ai3"))
        self.comboBox_detection.setItemText(4, _translate("Form", "ai4"))
        self.comboBox_detection.setItemText(5, _translate("Form", "ai5"))
        self.comboBox_detection.setItemText(6, _translate("Form", "ai6"))
        self.comboBox_detection.setItemText(7, _translate("Form", "ai7"))
        self.comboBox_pd_no_disk.setItemText(0, _translate("Form", "ai0"))
        self.comboBox_pd_no_disk.setItemText(1, _translate("Form", "ai1"))
        self.comboBox_pd_no_disk.setItemText(2, _translate("Form", "ai2"))
        self.comboBox_pd_no_disk.setItemText(3, _translate("Form", "ai3"))
        self.comboBox_pd_no_disk.setItemText(4, _translate("Form", "ai4"))
        self.comboBox_pd_no_disk.setItemText(5, _translate("Form", "ai5"))
        self.comboBox_pd_no_disk.setItemText(6, _translate("Form", "ai6"))
        self.comboBox_pd_no_disk.setItemText(7, _translate("Form", "ai7"))
        self.comboBox_test_detection.setItemText(0, _translate("Form", "ai0"))
        self.comboBox_test_detection.setItemText(1, _translate("Form", "ai1"))
        self.comboBox_test_detection.setItemText(2, _translate("Form", "ai2"))
        self.comboBox_test_detection.setItemText(3, _translate("Form", "ai3"))
        self.comboBox_test_detection.setItemText(4, _translate("Form", "ai4"))
        self.comboBox_test_detection.setItemText(5, _translate("Form", "ai5"))
        self.comboBox_test_detection.setItemText(6, _translate("Form", "ai6"))
        self.comboBox_test_detection.setItemText(7, _translate("Form", "ai7"))
        self.edit_wl_stop.setText(_translate("Form", "1570"))
        self.lineedit_scanning_speed.setText(_translate("Form", "20"))
        self.comboBox_plotting_coarse_scan.setItemText(0, _translate("Form", "Tapered fiber vs wl"))
        self.comboBox_plotting_coarse_scan.setItemText(1, _translate("Form", "Reference vs wl"))
        self.comboBox_plotting_coarse_scan.setItemText(2, _translate("Form", "Tap/ref"))
        self.comboBox_plotting_coarse_scan.setItemText(3, _translate("Form", "pre filter"))
        self.comboBox_plotting_coarse_scan.setItemText(4, _translate("Form", "Test norm"))
        self.lineEdit_avg_over_x_steps.setText(_translate("Form", "3"))
        self.btn_scan.setText(_translate("Form", "scan"))
        self.label_5.setText(_translate("Form", "Tap. fib. detection"))
        self.label_3.setText(_translate("Form", "Wl detection"))
        self.label_6.setText(_translate("Form", "Ref. detection"))
        self.label_4.setText(_translate("Form", "Test detection"))
        self.label_wavelength.setText(_translate("Form", "Wavelength [nm]"))
        self.edit_wl_start.setText(_translate("Form", "1520"))
        self.label.setText(_translate("Form", "Scanning speed [nm/s]"))
        self.plot_label.setText(_translate("Form", "Plot"))
        self.label_2.setText(_translate("Form", "Avg over # steps"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

